apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: lb-219-lightblue-dockerfiles
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lb-219-lightblue-dockerfiles
    app.kubernetes.io/part-of: lightblue-dockerfiles
  name: lb-219-lightblue-dockerfiles
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: lb-219-lightblue-dockerfiles
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: lb-219-lightblue-dockerfiles
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/dhaynes-tenant/lightblue-dockerfiles/lb-219-lightblue-dockerfiles@sha256:8ba4020d9692e9710aa1ee038f97fe572ae19a2ce04139a5682d462505337a79
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
