apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: lb-219-lightblue-dockerfiles
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lb-219-lightblue-dockerfiles
    app.kubernetes.io/part-of: lightblue-dockerfiles
  name: lb-219-lightblue-dockerfiles
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: lb-219-lightblue-dockerfiles
status:
  loadBalancer: {}
