apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: lb-218-lightblue-dockerfiles
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lb-218-lightblue-dockerfiles
    app.kubernetes.io/part-of: lightblue-dockerfiles
  name: lb-218-lightblue-dockerfiay7r
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: lb-218-lightblue-dockerfiles
    weight: 100
status: {}
